using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;
using Microsoft.Xna.Framework.Input;

namespace Pale_Roots_1
{
    // This state temporarily pauses the action to let the player pick a power-up.
    // It draws the active game frozen in the background and overlays the upgrade UI.
    public class LevelUpState : IGameState
    {
        private Game1 _game;

        // A brief timer to prevent the player from accidentally clicking an upgrade 
        // the exact millisecond the level-up screen appears if they were already spam-clicking to attack.
        private float _inputDelay = 0.5f;

        public LevelUpState(Game1 game)
        {
            _game = game;
        }

        public void LoadContent()
        {
            // Tell the AudioManager were in level up state
            _game.AudioManager.HandleMusicState(GameState.LevelUp);
        }

        public void Update(GameTime gameTime)
        {
            // We need the mouse visible so the player can click on their chosen card.
            _game.IsMouseVisible = true;

            // Tick down the safety delay timer. We only process clicks once this hits zero.
            if (_inputDelay > 0)
            {
                _inputDelay -= (float)gameTime.ElapsedGameTime.TotalSeconds;
            }
            else
            {
                HandleInput();
            }
        }

        private void HandleInput()
        {
            // Only fire the selection logic if the InputEngine detects a fresh left click.
            if (InputEngine.IsMouseLeftClick())
            {
                MouseState ms = Mouse.GetState();
                Rectangle screen = _game.GraphicsDevice.Viewport.Bounds;

                // Set up the hardcoded dimensions for our upgrade cards so we can build hitboxes for them.
                int cardWidth = 200;
                int cardHeight = 300;
                int spacing = 50;

                // Calculate the total width of the entire row of cards so we can perfectly center them on the screen.
                int totalWidth = (_game.CurrentUpgradeOptions.Count * cardWidth) + ((_game.CurrentUpgradeOptions.Count - 1) * spacing);
                int startX = (screen.Width / 2) - (totalWidth / 2);
                int startY = (screen.Height / 2) - (cardHeight / 2);

                // Loop through the list of random options generated by the UpgradeManager.
                for (int i = 0; i < _game.CurrentUpgradeOptions.Count; i++)
                {
                    // Mathematically build an invisible rectangle over where the UIManager is drawing this specific card.
                    Rectangle cardRect = new Rectangle(startX + (i * (cardWidth + spacing)), startY, cardWidth, cardHeight);

                    // If the mouse is inside this card's rectangle when they clicked...
                    if (cardRect.Contains(ms.Position))
                    {
                        // ...fire the specific action delegate attached to this upgrade (like boosting health or unlocking a spell).
                        _game.CurrentUpgradeOptions[i].ApplyAction.Invoke();

                        // Safety check to ensure we are still in the LevelUpState before swapping back to the gameplay.
                        if (_game.StateManager.CurrentState == this)
                        {
                            _game.StateManager.ChangeState(new GameplayState(_game));
                        }

                        // Wipe the input state so this click doesn't carry over into the game and cause an accidental attack.
                        InputEngine.ClearState();
                        break;
                    }
                }
            }
        }

        public void Draw(GameTime gameTime, SpriteBatch spriteBatch, GraphicsDevice graphicsDevice)
        {
            // First, draw the active game engine in the background using the camera matrix.
            // Because we aren't calling GameEngine.Update() in this state, the action is completely frozen.
            spriteBatch.Begin(SpriteSortMode.Deferred, BlendState.AlphaBlend, SamplerState.PointClamp, null, null, null, _game.GameEngine._camera.CurrentCameraTranslation);
            _game.GameEngine.Draw(gameTime, spriteBatch);
            spriteBatch.End();

            // Next, draw the level-up interface directly over the frozen game screen.
            // We pass the list of current options down to the UIManager so it knows what text and icons to display.
            spriteBatch.Begin();
            _game.UIManager.DrawLevelUpScreen(spriteBatch, graphicsDevice, _game.CurrentUpgradeOptions, _game.UpgradeManager);
            spriteBatch.End();
        }
    }
}