using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;
using System;
using System.Collections.Generic;

namespace Pale_Roots_1
{
    // This class is responsible for generating and managing the physical environment the game takes place in.
    // It builds out the floor tiles, places static and animated set dressing (like trees and ruins), 
    // and handles the procedural generation for the boundaries.
    public class LevelManager
    {
        private Game _game;

        // Lists tracking all the active entities generated by this manager.
        public List<Enemy> enemies = new List<Enemy>();
        public List<WorldObject> MapObjects = new List<WorldObject>();

        // Variables to handle drawing the actual ground and objects.
        public TileLayer CurrentLevel { get; private set; }
        private Texture2D _groundSheet;
        private Texture2D _animatedObjectSheet;
        private Texture2D _staticObjectSheet;

        public LevelManager(Game game)
        {
            _game = game;
        }

        public void LoadLevel(int index)
        {
            // Pull the massive texture sheets that contain all our environment art into memory.
            _groundSheet = _game.Content.Load<Texture2D>("MainLev2.0");
            _animatedObjectSheet = _game.Content.Load<Texture2D>("Objects_animated");
            _staticObjectSheet = _game.Content.Load<Texture2D>("more Objects");

            // Temporarily assign the ground sheet to our static helper class so the tile generator can access it.
            Helper.SpriteSheet = _groundSheet;
            InitializeGameWorld(index);
        }

        private void InitializeGameWorld(int levelIndex)
        {
            // Define a massive grid for the battlefield (60 tiles wide by 34 tiles high).
            int width = 60;
            int height = 34;
            int[,] map = new int[height, width];

            // Fill every single slot in that grid with a basic grass tile (ID 0).
            for (int y = 0; y < height; y++)
            {
                for (int x = 0; x < width; x++)
                {
                    map[y, x] = 0;
                }
            }

            // Ask the static LevelDataLibrary for the specific tile mapping rules for this level index.
            List<TileRef> palette = LevelDataLibrary.GetLevelPalette(levelIndex);

            // Construct the physical TileLayer object that will handle drawing this massive grid.
            CurrentLevel = new TileLayer(map, palette, 64, 32);

            // Calculate the absolute center point of our massive grid.
            float centerX = width / 2f;
            float centerY = height / 2f;

            // Define an invisible safe zone in the center of the map. 
            // We want the fighting area totally clear of obstacles.
            float safeRadiusX = 22f;
            float safeRadiusY = 11f;

            // Loop through the entire map again to build the procedural borders.
            for (int y = 0; y < height; y++)
            {
                for (int x = 0; x < width; x++)
                {
                    // Calculate exactly how far away this tile is from the center.
                    float dx = Math.Abs(x - centerX);
                    float dy = Math.Abs(y - centerY);

                    // If the tile is outside of our defined safe zone, calculate exactly how far outside it is.
                    float excessX = Math.Max(dx - safeRadiusX, 0);
                    float excessY = Math.Max(dy - safeRadiusY, 0);
                    float distanceOutsideBox = (float)Math.Sqrt(excessX * excessX + excessY * excessY);

                    // If we are definitely outside the safe fighting area...
                    if (distanceOutsideBox > 0)
                    {
                        // The further away from the center we get, the higher the chance we spawn an object.
                        // This creates a natural-looking border that gets denser near the edges.
                        float chance = distanceOutsideBox / 4.5f;
                        chance += CombatSystem.RandomFloat(-0.2f, 0.2f); // Add a tiny bit of noise.

                        if (CombatSystem.RandomFloat() < chance)
                        {
                            // Calculate the real-world pixel coordinates for this tile.
                            Vector2 pos = new Vector2(x * 64, y * 64);

                            // Nudge the position slightly off-grid so the forest looks natural, not like a chessboard.
                            pos.X += CombatSystem.RandomInt(-24, 24);
                            pos.Y += CombatSystem.RandomInt(-24, 24);

                            // Pick a random nature asset (like a tree or bush) from the Data Library and spawn it.
                            string randomNature = LevelDataLibrary.NatureObjects[CombatSystem.RandomInt(0, LevelDataLibrary.NatureObjects.Length)];
                            CreateStaticObject(randomNature, pos, _staticObjectSheet, false);
                        }
                    }
                }
            }

            // Once the procedural border is built, manually place the important set pieces.
            PlaceLandMarks();
        }

        private bool IsSpaceOccupied(Vector2 pos, float minGap)
        {
            // Loop through every object we have already placed in the world.
            foreach (var obj in MapObjects)
            {
                // Calculate a rough collision circle based on the object's width and scale.
                float objectRadius = (obj.spriteWidth * (float)obj.Scale) / 2.5f;
                float safeDistance = minGap + objectRadius;

                // If our requested spawn point is inside that safety circle, reject the placement.
                if (Vector2.Distance(pos, obj.position) < safeDistance)
                {
                    return true;
                }
            }
            return false;
        }

        private void PlaceLandMarks()
        {
            // Hardcode the specific locations for major narrative set pieces.
            Vector2 centerPos = new Vector2(30 * 64, 17 * 64);
            CreateAnimatedObject("Tree_Dead_Large", centerPos, _animatedObjectSheet, 4);

            Vector2 kingPos = new Vector2(40 * 64, 16 * 64);
            CreateStaticObject("Skellington", kingPos, _staticObjectSheet, false);

            Vector2 bigRuinPos = new Vector2(8 * 64, 6 * 64);
            CreateStaticObject("Ruins_Column", bigRuinPos, _staticObjectSheet, false);
            CreateStaticObject("Big_Rock", bigRuinPos + new Vector2(200, 190), _staticObjectSheet, false);

            CreateStaticObject("Smaller_Ruin", new Vector2(50 * 64, 7 * 64), _staticObjectSheet, false);
            CreateStaticObject("Smaller_Ruin", new Vector2(48 * 64, 26 * 64), _staticObjectSheet, false);

            // Once the main landmarks are down, ask the system to sprinkle random debris around them.
            FillZones(centerPos);
        }

        private void FillZones(Vector2 centerPos)
        {
            int attempts = 0;
            int maxItems = 60;
            int itemsPlaced = 0;

            // Keep trying to place random debris until we hit our quota or our safety counter maxes out.
            while (itemsPlaced < maxItems && attempts < 1000)
            {
                attempts++;

                // Pick a totally random tile somewhere within the main play area.
                int tx = CombatSystem.RandomInt(6, 54);
                int ty = CombatSystem.RandomInt(6, 28);
                Vector2 pos = new Vector2(tx * 64, ty * 64);

                // Nudge it off the grid lines for a natural look.
                pos += new Vector2(CombatSystem.RandomInt(-20, 20), CombatSystem.RandomInt(-20, 20));

                float distToCenter = Vector2.Distance(pos, centerPos);

                // If this random spot is already covered by a tree or ruin, skip this attempt.
                if (IsSpaceOccupied(pos, 80f)) continue;

                string assetToSpawn = "";
                bool isSolid = false;


                // We divide the map into invisible zones to decide what kind of debris should spawn there.

                // If it's near the dead center tree, spawn bones.
                if (distToCenter < 350 && distToCenter > 100)
                {
                    assetToSpawn = LevelDataLibrary.BoneObjects[CombatSystem.RandomInt(0, LevelDataLibrary.BoneObjects.Length)];
                }
                // If it's on the far left side of the map, spawn graves.
                else if (tx < 22)
                {
                    assetToSpawn = LevelDataLibrary.GraveObjects[CombatSystem.RandomInt(0, LevelDataLibrary.GraveObjects.Length)];
                }
                // If it's on the far right side of the map, heavily favor ruins.
                else if (tx > 38)
                {
                    if (CombatSystem.RandomInt(0, 100) > 70)
                        assetToSpawn = LevelDataLibrary.RuinObjects[CombatSystem.RandomInt(0, LevelDataLibrary.RuinObjects.Length)];
                    else
                        assetToSpawn = LevelDataLibrary.NatureObjects[CombatSystem.RandomInt(0, LevelDataLibrary.NatureObjects.Length)];

                }
                // Anywhere else, make it a 50/50 split between bones and nature.
                else
                {
                    if (CombatSystem.RandomInt(0, 100) > 50)
                        assetToSpawn = LevelDataLibrary.BoneObjects[CombatSystem.RandomInt(0, LevelDataLibrary.BoneObjects.Length)];
                    else
                        assetToSpawn = LevelDataLibrary.NatureObjects[CombatSystem.RandomInt(0, LevelDataLibrary.NatureObjects.Length)];
                }

                // If we successfully picked an asset to spawn.
                if (assetToSpawn != "")
                {
                    // Do one final check to make sure we aren't spawning two identical skulls or trees right next to each other.
                    if (IsTooCloseToIdentical(assetToSpawn, pos, 500f)) continue;

                    CreateStaticObject(assetToSpawn, pos, _staticObjectSheet, isSolid);
                    itemsPlaced++;
                }
            }
        }

        private bool IsTooCloseToIdentical(string assetName, Vector2 pos, float minDistance)
        {
            // Loop through our existing objects and see if an identical one is sitting too close.
            foreach (var obj in MapObjects)
            {
                if (obj.AssetName == assetName)
                {
                    if (Vector2.Distance(pos, obj.position) < minDistance) return true;
                }
            }
            return false;
        }

        private void CreateStaticObject(string assetName, Vector2 position, Texture2D sheet, bool isSolid)
        {
            // Ask the Helper to find the specific rectangle containing this asset on our massive sprite sheet.
            Rectangle data = Helper.GetSourceRect(assetName);

            // Generate the physical object, apply the texture data, and add it to our tracking list.
            var obj = new WorldObject(_game, sheet, position, 1, isSolid);
            obj.AssetName = assetName;
            obj.SetSpriteSheetLocation(data);
            MapObjects.Add(obj);
        }

        private void CreateAnimatedObject(string assetName, Vector2 position, Texture2D sheet, int frames)
        {
            Rectangle data = Helper.GetSourceRect(assetName);
            var obj = new WorldObject(_game, sheet, position, frames, false);
            obj.SetSpriteSheetLocation(data);
            MapObjects.Add(obj);
        }

        public void GenerateBossArena()
        {
            // Use the exact same grid dimensions as the main game so the arena feels massive.
            int width = 60;
            int height = 34;
            int[,] map = new int[height, width];

            // Fill the entire floor with standard grass so there is no black void at the edges of the screen.
            for (int y = 0; y < height; y++)
            {
                for (int x = 0; x < width; x++)
                {
                    map[y, x] = 0;
                }
            }

            // We reuse the palette from Level 0 so the grass color and style perfectly matches the main game.
            List<TileRef> palette = LevelDataLibrary.GetLevelPalette(0);
            CurrentLevel = new TileLayer(map, palette, 64, 32);

            // Wipe out any existing objects in the manager just in case.
            MapObjects.Clear();

            // Calculate a massive circle in the center of the map to act as the fighting space.
            Vector2 center = new Vector2(width * 64 / 2, height * 64 / 2);
            float arenaRadius = 900f;

            // Loop through the whole map area to generate the dense tree line.
            for (int y = 0; y < height; y++)
            {
                for (int x = 0; x < width; x++)
                {
                    Vector2 tilePos = new Vector2(x * 64, y * 64);
                    float dist = Vector2.Distance(tilePos, center);

                    // If this tile falls OUTSIDE our calculated fighting circle...
                    if (dist > arenaRadius)
                    {
                        // Roll an 80% chance to spawn a tree on it. 
                        // We use a high chance with some noise so the border feels like a thick, natural forest,
                        // rather than a mathematically perfect artificial wall.
                        if (CombatSystem.RandomInt(0, 10) < 8)
                        {

                            string[] natureAssets = LevelDataLibrary.NatureObjects;
                            string randomAsset = natureAssets[CombatSystem.RandomInt(0, natureAssets.Length)];

                            Vector2 pos = tilePos + new Vector2(CombatSystem.RandomInt(-20, 20), CombatSystem.RandomInt(-20, 20));
                            CreateStaticObject(randomAsset, pos, _staticObjectSheet, false);
                        }
                    }
                }
            }
        }

        public void Update(GameTime gameTime, Player player)
        {
            // Update all standard enemies managed by this level instance.
            foreach (Enemy enemy in enemies)
            {
                enemy.CurrentCombatPartner = player;
                enemy.Update(gameTime);
            }

            // Clean up the list by removing any enemies that have fully completed their death sequence.
            enemies.RemoveAll(e => e.LifecycleState == Enemy.ENEMYSTATE.DEAD);

            // Update all physical objects (this mostly handles stepping the frames for animated objects like the dead tree).
            foreach (var obj in MapObjects)
            {
                obj.Update(gameTime);
            }
        }

        public void Draw(SpriteBatch spriteBatch)
        {
            if (CurrentLevel != null)
            {
                CurrentLevel.Draw(spriteBatch);
            }
        }
    }
}